name: Test
permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-26
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Clean SwiftPM metadata
      run: rm -rf Launchpad.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
      
    - name: Build Launchpad
      run: |
        xcodebuild clean build \
          -project Launchpad.xcodeproj \
          -scheme Launchpad \
          -configuration Release \
          -destination 'platform=macOS,arch=arm64' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Run Tests
      run: |
        xcodebuild test \
          -project Launchpad.xcodeproj \
          -scheme Launchpad \
          -destination 'platform=macOS,arch=arm64' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
